### ISSUE TITLE
Docs and Info

### ISSUE THREAD

**Issue by CraigChamberlain** [slaveOftime/Fun.OData#22]
Hi,

This looks a really useful library.  I'm just thinking about using this and Giraffe for the first time and want to be sure I'm interpreting it all correctly.

I think the docs are the best I've found for an F# OData module by some way but I wondered if you help me understand them and the project if I could help with the docs?

I'm going to work through this bit on CE as I've a bit of prerequisite learning to get to grips with this.
https://fsharpforfunandprofit.com/posts/computation-expressions-intro/

Do you consider this project as production ready?  I was particularly interested in the Server part of this but there is a mention in the docs that this is deprecated?  Do you use some kind of hybrid c# implementation now e.g. https://learn.microsoft.com/en-us/odata/webapi-8/tutorials/basic-crud-in-fsharp?tabs=net60%2Cvisual-studio 
no giraffe?

**Comment by albertwoo** [comment]
If you are intrested in the server part, then this project is not for you. The reason it is deprecated is because the OData updated its internal stuff which breaked my original implementation and it is not easy to follow up their new things. In another point of view, I think that just use old school controller with fsharp can also serve the purpose, so I decided to deprecate the server and giraffe support. 

I am not using csharp and fsharp for odata, just use controller style with fsharp and the odata is working as expected, at least for query.

**Comment by CraigChamberlain** [comment]
This is supper helpful thank you.  I'm having a bit of a second wind with F#.  I love writing it but got a bit lost in the UI space (Fable + Elmish) a few years ago and found it a bit of a dead end.  I'll be glad to use F# again but be more selective where.
